Implement Error Reporting service and ResourceProvider
mateuszCabala95/CodersCamp2020.Bomberman pull request #11
Opened 2021-01-22 17:09 UTC by kgutka

2021-01-22 18:52 UTC, jkopyto requested changes

2021-01-22 18:52 UTC, jkopyto commented on src/services/ResourceProvider/ResourceProvider.ts
> +    get(resourceName: string): void {
```suggestion
    get(resourceName: string): string {
```

`string` powinno przejść, a jak nie to zostaw void

2021-01-22 18:52 UTC, jkopyto commented on src/services/ErrorReporting/ConsoleReporting.ts
> +        }
Trochę dużo kombinacji tak mi się wydaje. Wystarczy:

```
export default class ConsoleReporting extends ErrorReporting {
    report(error?: ReportMsgType | Record<string, unknown>): void {
        console.error(error)
    }
}
```

2021-01-22 18:52 UTC, jkopyto commented on src/app/App.ts
> +    registerDependencyFunc()
Providery zarejestruj w `src/index-app.ts` - to jest nasz taki entry point do całej apki

2021-01-22 18:57 UTC, kgutka commented on src/services/ResourceProvider/ResourceProvider.ts
> +    get(resourceName: string): void {
zrobione

2021-01-22 18:59 UTC, kgutka commented on src/services/ErrorReporting/ConsoleReporting.ts
> +        }
zrobione

2021-01-22 19:00 UTC, kgutka commented on src/app/App.ts
> +    registerDependencyFunc()
czyli wyczyścić cały plik App.ts

2021-01-22 19:10 UTC, kgutka commented on src/app/App.ts
> +    registerDependencyFunc()
zrobione

2021-01-22 19:12 UTC, kgutka commented on src/services/ErrorReporting/ConsoleReporting.ts
> +        }
czemu argument error ma być opcjonalny?

2021-01-22 20:14 UTC, jkopyto commented on src/services/ErrorReporting/ConsoleReporting.ts
> +        }
Bo może czasem być po prostu `undefined`. Czasami libki mogę rzucić taki error, albo podczas wykonywania czegoś w try catch tak sie może zdarzyć.  Jak zrobione to czekam na pusha :)

2021-01-23 19:47 UTC, jkopyto approved these changes

2021-01-23 19:48 UTC, merged