Add routing
mateuszCabala95/CodersCamp2020.Bomberman pull request #13
Opened 2021-01-22 19:13 UTC by mateuszCabala95

2021-01-22 20:20 UTC, jkopyto requested changes

2021-01-22 20:20 UTC, jkopyto commented on src/services/Router.ts
> +        this.appContainer = document.querySelector("#app")
Wynieś do osobnej metody i wywołać ją w `render`

2021-01-22 20:20 UTC, jkopyto commented on src/services/Router.ts
> +        this.render()
Nie możemy wywoływać render w konstruktorze. Lepiej to zrobić tam gdzie będzie tworzona instancja Routera, wtedy to będzie mniej więcej tak:
```
const Router = new Router()
Router.render()
```

2021-01-22 20:20 UTC, jkopyto commented on src/services/Router.ts
> +            case("/" || "") : {
```suggestion
            case "/" :
            case "" : {
```

O ile eslint tego nie zablokuje. Jak zablokuje to wyłącz mu rule za to odpowiedzialny

2021-01-22 20:20 UTC, jkopyto commented on src/services/Router.ts
> +        switch (this.path.hash) {
Path jest zestawiany tylko raz - w konstruktorze, więc cały czas będzie taki sam. A nie lepiej jakbyś wyciągał hash z eventu, który leci?

2021-01-22 20:20 UTC, jkopyto commented on src/services/Router.ts
> +            // in case wrong URL should redirect to main page
Nie widzę potrzeby zostawiania tu komentarzy. Kod sam się obroni

2021-01-22 21:09 UTC, mateuszCabala95 commented on src/services/Router.ts
> +        switch (this.path.hash) {
Tutaj mam problem, z eventu **HashChangeEvent** moge pobrać jedynie całą ścieżkę 
`    initPage = (e: HashChangeEvent): void => {
        switch (e.newURL) {

2021-01-25 11:27 UTC, jkopyto commented on src/services/Router.ts
> +        switch (this.path.hash) {
`e.target.location.hash`

2021-01-27 09:31 UTC, jkopyto approved these changes

2021-01-27 09:31 UTC, merged