Installing and connfiguring moddernizr into the project
mateuszCabala95/CodersCamp2020.Bomberman pull request #22
Opened 2021-01-25 19:23 UTC by adam-kostuch

2021-02-01 20:17 UTC, mateuszCabala95 approved these changes

2021-02-01 21:15 UTC, jkopyto requested changes

2021-02-01 21:15 UTC, jkopyto commented on jest.config.ts
> +  testEnvironment: "jsdom"
Na pewno chcemy pozostałe rzeczy wyrzucić z configa?

2021-02-01 21:15 UTC, jkopyto commented on src/index-app.ts
> +const registerDependencyFunc = () => {
```suggestion
const registerDependencyFunc = (): void => {
```

2021-02-01 21:15 UTC, jkopyto commented on src/index.css
> +/*# sourceMappingURL=index.css.map */
Komentarz chyba niepotrzebny

2021-02-01 21:15 UTC, jkopyto commented on src/index.css.map
> +{
Czemu plik .map powstał w `src/`?

2021-02-01 21:15 UTC, jkopyto commented on src/services/MobileDetection/__tests__/MobileDetection.spec.ts
> +// @ts-nocheck
Z tym komentem to nie przejdzie

2021-02-01 21:15 UTC, jkopyto commented on src/services/MobileDetection/__tests__/MobileDetection.spec.ts
> +import { isMobile } from "mobile-device-detect"
Nie używasz tego nigdzie

2021-02-02 15:06 UTC, adam-kostuch commented on jest.config.ts
> +  testEnvironment: "jsdom"
Przy zmianie na tę formę widziałem żadnych różnic w kodzie, więc wywaliłem. Faktycznie to przywrócę, bo to, że mi działa nie oznacza, że każdemu będzie.

2021-02-02 15:08 UTC, adam-kostuch commented on src/index-app.ts
> +const registerDependencyFunc = () => {
Tutaj, nie wiem nawet co się stało, że tego nie ma. Wydawało mi się, że nie ruszałem tego fragmentu.

2021-02-02 15:12 UTC, adam-kostuch commented on src/index.css
> +/*# sourceMappingURL=index.css.map */
Zmienione lokalnie

2021-02-02 15:14 UTC, adam-kostuch commented on src/index.css.map
> +{
Wydaje mi się, że przy pobieraniu nowych modułów, które próbowałem zaimplementować, a końcowo odinstalowałem nie usunąłem wszystkiego.

2021-02-02 15:14 UTC, adam-kostuch commented on src/services/MobileDetection/__tests__/MobileDetection.spec.ts
> +import { isMobile } from "mobile-device-detect"
Usunałem lokalnie, ale tylko na jednym branchu wcześniej, teraz poprawione

2021-02-02 15:17 UTC, adam-kostuch commented on src/services/MobileDetection/__tests__/MobileDetection.spec.ts
> +// @ts-nocheck
Jak zmienię na `//@ts-ignore`, albo na  dodam `// eslint-disable-next-line @typescript-eslint/ban-ts-comment`, co blokuje mi błąd to przejdzie?

2021-02-09 11:02 UTC, jkopyto commented on src/services/MobileDetection/__tests__/MobileDetection.spec.ts
> +// @ts-nocheck
Daj samo `// eslint-disable-next-line` nad linią o którą się eslint pluje i powinno być okej

2021-02-11 17:03 UTC, kgutka commented on src/services/MobileDetection/__tests__/MobileDetection.spec.ts
> +// @ts-nocheck
Zmieniłeś to finalnie na `// eslint-disable-next-line`, ale `// @ts-nocheck` został. Chyba tego miało nie być

2021-02-11 17:18 UTC, adam-kostuch commented on src/services/MobileDetection/__tests__/MobileDetection.spec.ts
> +// @ts-nocheck
Bez `// @ts-nocheck`, zwraca błąd, że nie można zmienić `readonly property` przy `window.screen.orientation = { type }`. Dopiero 2 linijka pomogła, ale sama w sobie też błąd wywalała, więc musiałem dodać `// eslint-disable-next-line` i pomogło na wszystkie błędy.

2021-02-11 17:59 UTC, kgutka approved these changes

2021-02-11 18:20 UTC, merged