Joystick tests
mateuszCabala95/CodersCamp2020.Bomberman pull request #39
Opened 2021-02-03 11:58 UTC by kacperzolkiewski

2021-02-03 21:28 UTC, adam-kostuch reviewed
It would be great if You could create `__tests__` folder in `src/joystick` directory, just to keep all of the tests in there

2021-02-07 14:34 UTC, kgutka requested changes
Add `__tests__` directory and put `joystick.spec.ts` inside it
- I didn't see the previous comment about the same issue. Please do it, pull recent changes from master and then we will merge

2021-02-10 16:26 UTC, adam-kostuch approved these changes

2021-02-14 11:06 UTC, adam-kostuch approved these changes

2021-02-15 13:21 UTC, adam-kostuch requested changes

2021-02-15 13:21 UTC, adam-kostuch commented on src/boot/boot.ts
>        // validate if player can move there (walls) - TODO
We have to delete all of the remaining comments.

2021-02-15 16:34 UTC, kacperzolkiewski commented on src/boot/boot.ts
>        // validate if player can move there (walls) - TODO
ok

2021-02-15 18:51 UTC, kgutka approved these changes

2021-02-15 18:52 UTC, adam-kostuch approved these changes

2021-02-15 21:51 UTC, adam-kostuch requested changes
Wait with merging for `update-code` to be merged first. Then rebase changes, because i moved `src/node/__tests__/node.mock.ts` and `src/node/__tests__/index.ts` into new `./mocks` directory. 😄

2021-02-16 01:13 UTC, kgutka commented
Closes #55

2021-02-16 09:37 UTC, adam-kostuch requested changes

2021-02-16 09:37 UTC, adam-kostuch commented on src/Player/components/draw/draw.ts
> +    // CanvasLayer.Foreground2.DrawGrounds()
If those parameters won't be used later, we should delete them

2021-02-16 13:54 UTC, kgutka commented on src/Player/components/draw/draw.ts
> +    // CanvasLayer.Foreground2.DrawGrounds()
done

2021-02-16 18:02 UTC, adam-kostuch approved these changes

2021-02-16 18:15 UTC, merged