Setup project
mateuszCabala95/CodersCamp2020.Bomberman pull request #5
Opened 2021-01-21 08:19 UTC by mateuszCabala95

Zainstalowano i skonfigurowano TSLint i Prettier, zainstalowano Webpack, skonfigurowano jedynie server. Do dodania została jeszcze transpilacja SCSS do CSS

2021-01-21 20:45 UTC, jkopyto requested changes

2021-01-21 20:45 UTC, jkopyto commented on .env
> +NODE_ENV=production
To na razie bez tego. Zostaw ten plik pusty

2021-01-21 20:45 UTC, jkopyto commented on src/index-app.ts
> +
Tutaj będzie można rejestrować serwisy do providera. To tak tylko informacyjnie pisze

2021-01-21 20:45 UTC, jkopyto commented on tslint.json
> +        "tslint-config-prettier"
- [ ] Chciałbym żebyśmy mieli plik `.eslintrc.js`, który bedzie zawierał konfiguracje eslinta.
- [ ] Chciałbym, żeby extend wyglądał tak (będzie trzeba doinstalować pluginy): 
```
extends: [
    "eslint:recommended",
    "plugin:react/recommended", // Uses the recommended rules from @eslint-plugin-react
    "plugin:@typescript-eslint/eslint-recommended", // Uses the recommended rules from the @typescript-eslint/eslint-plugin
    "plugin:@typescript-eslint/recommended", // Uses the recommended rules from the @typescript-eslint/eslint-plugin
    "prettier/@typescript-eslint", // Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier
  ]
  ```
  - [ ] Jako parser ustawisz: `parser: "@typescript-eslint/parser"`
  

Generalnie to jak masz zainstalowanego eslinta globalnie, albo chyba wystarczy, że w paczce będzie jako dev-dependency to robisz `npm eslint --init` i generujesz wstępny plik konfiguracyjny. Potem go tylko szlifujesz

2021-01-21 20:45 UTC, jkopyto commented on package.json
> +    "ts-prettier-check": "tslint-config-prettier-check ./tslint.json",
To raczej nie potrzebne nam bedzie. Docelowo nie bedziemy korzystali z tslint. Wszystko za nas zrobi ogólny eslint

2021-01-21 21:37 UTC, mateuszCabala95 commented on tslint.json
> +        "tslint-config-prettier"
Usunąć całkowicie tslint.json ?

2021-01-21 21:37 UTC, jkopyto commented on tslint.json
> +        "tslint-config-prettier"
tak

2021-01-22 16:43 UTC, jkopyto requested changes

2021-01-22 16:43 UTC, jkopyto commented on .eslintrc.js
> +    es2021: true
```suggestion
    es2021: true,
    jest: true,
    node: true
```

2021-01-22 16:43 UTC, jkopyto commented on .eslintrc.js
> +    ecmaVersion: 12
```suggestion
    ecmaVersion: 2020, // Allows for the parsing of modern ECMAScript features
    sourceType: "module", // Allows for the use of imports
    ecmaFeatures: {
      arrowFunctions: true,
    },
```

2021-01-22 16:43 UTC, jkopyto commented on .eslintrc.js
> +    '@typescript-eslint'
```suggestion
    '@typescript-eslint', "prettier"
```

2021-01-22 16:43 UTC, jkopyto commented on .eslintrc.js
> +  }
```suggestion
    "no-extra-semi": "error",
    "no-console": "warn",
    
    "no-use-before-define": "off"
    "@typescript-eslint/no-use-before-define": ["error"]
    "@typescript-eslint/explicit-function-return-type": "off"
  },
  overrides: [
    {
      files: ["**/*.ts", "**/*.tsx"],
      rules: {
        "@typescript-eslint/explicit-function-return-type": [
          "warn",
          {
            allowExpressions: true,
          },
        ],
      },
    },
    {
      files: ["**/*.js", "**/*.jsx"],
      plugins: ["@typescript-eslint"],
      rules: {
        "@typescript-eslint/explicit-function-return-type": 0,
      },
    },
  ],
```

2021-01-22 16:52 UTC, merged